# -*- coding: utf-8 -*-
"""Streamlit_crop_predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiwK4kERE3hHjTpraPPNR9uqH7AjupqX
"""

import streamlit as st
import requests
from geopy.geocoders import Nominatim

# === Configuration ===
OPENWEATHER_API_KEY = "a0d558e1b239783fa28304f20f3dc7af"

# === Get Coordinates from Address ===
def get_coordinates(address):
    geolocator = Nominatim(user_agent="geoapi")
    location = geolocator.geocode(address)
    if location:
        return location.latitude, location.longitude
    else:
        return None, None

# === Get Weather Data from OpenWeatherMap ===
def get_weather_data(lat, lon):
    url = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={OPENWEATHER_API_KEY}&units=metric"
    res = requests.get(url)
    data = res.json()
    return {
        "Temperature (°C)": data["main"]["temp"],
        "Humidity (%)": data["main"]["humidity"],
        "Rainfall (mm)": data.get("rain", {}).get("1h", 0)
    }

# === Get Soil pH from SoilGrids ===
def get_soil_ph(lat, lon):
    url = f"https://rest.isric.org/soilgrids/v2.0/properties/query?lon={lon}&lat={lat}&property=phh2o&value=mean"
    res = requests.get(url)
    data = res.json()
    ph_value = data['properties']['phh2o']['layers'][0]['depths'][0]['values']['mean']
    return round(ph_value / 10, 1)  # ISRIC returns pH * 10

# === Streamlit UI ===
st.title("🌾 Real-time Crop_Predictor")
address = st.text_input("Enter location (e.g., Ibadan, Nigeria):")

if address:
    lat, lon = get_coordinates(address)
    if lat and lon:
        st.success(f"📍 Coordinates: {lat:.4f}, {lon:.4f}")

        weather = get_weather_data(lat, lon)
        soil_ph = get_soil_ph(lat, lon)

        st.subheader("🌦️ Weather Data")
        for key, value in weather.items():
            st.write(f"{key}: {value}")

        st.subheader("🌱 Soil Data")
        st.write(f"Soil pH: {soil_ph}")
    else:
        st.error("Couldn't find the location.")